import os
REGION = os.environ.get("AWS_DEFAULT_REGION", "us-east-1")
ENVIRONMENT = os.environ.get("ENVIRONMENT", "hackathon")
TICKETS_TABLE = os.environ.get("TICKETS_TABLE", f"{ENVIRONMENT}_it_tickets")
PATTERNS_TABLE = os.environ.get("PATTERNS_TABLE", f"{ENVIRONMENT}_ticket_patterns")
RESOLUTIONS_TABLE = os.environ.get("RESOLUTIONS_TABLE", f"{ENVIRONMENT}_resolutions")
RUNBOOK_BUCKET = os.environ.get("RUNBOOK_BUCKET", f"{ENVIRONMENT}-it-ticket-runbooks")
BEDROCK_MODEL_ID = os.environ.get("BEDROCK_MODEL_ID", "us.amazon.nova-lite-v1:0")
BEDROCK_REGION = os.environ.get("BEDROCK_REGION", REGION)
CONFIDENCE_THRESHOLD = int(os.environ.get("CONFIDENCE_THRESHOLD", "80"))
